import '../models/crm_models.dart';

class CrmDataService {
  static final List<CrmPatient> _patients = [
    CrmPatient(
      id: 'p1',
      name: 'Rahul Das',
      uhid: 'PT000123',
      phone: '9830011223',
      email: 'rahul.das@gmail.com',
      address: '123, Main Road, Kolkata - 700016',
      age: 32,
      gender: 'Male',
      bloodGroup: 'B+',
      lastVisit: DateTime.parse('2026-09-09T10:30:00'),
      status: 'Active',
    ),
    CrmPatient(
      id: 'p2',
      name: 'Priya Sharma',
      uhid: 'PT000124',
      phone: '9123456789',
      email: 'priya.s@example.com',
      address: '45 Park Street, Kolkata',
      age: 28,
      gender: 'Female',
      bloodGroup: 'O+',
      lastVisit: DateTime.parse('2026-09-08T11:00:00'),
      status: 'Active',
    ),
    CrmPatient(
      id: 'p3',
      name: 'Suman Roy',
      uhid: 'PT000125',
      phone: '9876543210',
      email: 'suman.roy@example.com',
      address: 'Salt Lake Sector 5, Kolkata',
      age: 45,
      gender: 'Male',
      bloodGroup: 'A-',
      lastVisit: DateTime.parse('2026-09-05T14:15:00'),
      status: 'Active',
    ),
    CrmPatient(
      id: 'p4',
      name: 'Neha Patel',
      uhid: 'PT000126',
      phone: '9901122334',
      email: 'neha.p@example.com',
      address: 'New Town, Kolkata',
      age: 31,
      gender: 'Female',
      bloodGroup: 'AB+',
      lastVisit: DateTime.parse('2026-09-09T09:45:00'),
      status: 'Active',
    ),
    CrmPatient(
      id: 'p5',
      name: 'Karan Mehta',
      uhid: 'PT000127',
      phone: '9123044567',
      email: 'karan.m@example.com',
      address: 'Ballygunge, Kolkata',
      age: 38,
      gender: 'Male',
      bloodGroup: 'O-',
      lastVisit: DateTime.parse('2026-09-07T16:20:00'),
      status: 'Active',
    ),
    CrmPatient(
      id: 'p6',
      name: 'Anita Singh',
      uhid: 'PT000128',
      phone: '9876509876',
      email: 'anita.s@example.com',
      address: 'Dum Dum, Kolkata',
      age: 26,
      gender: 'Female',
      bloodGroup: 'B-',
      lastVisit: DateTime.parse('2026-09-09T12:10:00'),
      status: 'Follow Up',
    ),
    CrmPatient(
      id: 'p7',
      name: 'Deepak Shaw',
      uhid: 'PT000129',
      phone: '9830098765',
      email: 'deepak.s@example.com',
      address: 'Howrah',
      age: 52,
      gender: 'Male',
      bloodGroup: 'A+',
      lastVisit: DateTime.parse('2026-09-03T10:05:00'),
      status: 'Active',
    ),
    CrmPatient(
      id: 'p8',
      name: 'Pooja Verma',
      uhid: 'PT000130',
      phone: '9123098734',
      email: 'pooja.v@example.com',
      address: 'Rajarhat, Kolkata',
      age: 29,
      gender: 'Female',
      bloodGroup: 'O+',
      lastVisit: DateTime.parse('2026-09-06T15:30:00'),
      status: 'Follow Up',
    ),
    CrmPatient(
      id: 'p9',
      name: 'Amit Kumar',
      uhid: 'PT000131',
      phone: '9876512345',
      email: 'amit.k@example.com',
      address: 'Behala, Kolkata',
      age: 41,
      gender: 'Male',
      bloodGroup: 'B+',
      lastVisit: DateTime.parse('2026-09-01T11:20:00'),
      status: 'Inactive',
    ),
    CrmPatient(
      id: 'p10',
      name: 'Sunita Mishra',
      uhid: 'PT000132',
      phone: '9901198765',
      email: 'sunita.m@example.com',
      address: 'Alipore, Kolkata',
      age: 35,
      gender: 'Female',
      bloodGroup: 'A-',
      lastVisit: DateTime.parse('2026-08-25T10:00:00'),
      status: 'Inactive',
    ),
  ];

  static Future<List<CrmPatient>> getPatients() async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 500));
    return List.from(_patients);
  }

  static Future<void> addPatient(CrmPatient patient) async {
    await Future.delayed(const Duration(milliseconds: 300));
    _patients.insert(0, patient);
  }

  static Future<void> updatePatient(CrmPatient updatedPatient) async {
    await Future.delayed(const Duration(milliseconds: 300));
    final index = _patients.indexWhere((p) => p.id == updatedPatient.id);
    if (index != -1) {
      _patients[index] = updatedPatient;
    }
  }

  static Future<void> deletePatient(String patientId) async {
    await Future.delayed(const Duration(milliseconds: 300));
    _patients.removeWhere((p) => p.id == patientId);
  }

  static Future<List<CrmNote>> getNotesForPatient(String patientId) async {
    await Future.delayed(const Duration(milliseconds: 300));
    return [
      CrmNote(
        id: 'n1',
        patientId: patientId,
        note:
            'Patient has a history of hypertension. Advise regular follow-up.',
        author: 'Dr. Sen',
        createdAt: DateTime.parse('2026-09-09T10:30:00'),
      ),
    ];
  }

  static Future<List<CrmAppointment>> getAppointments() async {
    await Future.delayed(const Duration(milliseconds: 500));
    return [
      CrmAppointment(
        id: 'APT20260909001',
        patientName: 'Rahul Das',
        patientAge: '32 Y',
        patientGender: 'Male',
        patientPhone: '9830011223',
        patientEmail: 'rahul.das@example.com',
        location: 'Kolkata, West Bengal',
        doctorName: 'Dr. Sen',
        appointmentType: 'General Consultation',
        time: '09:00 AM',
        date: '09 Sep 2026',
        status: 'Completed',
        consultationFee: '₹ 500',
        paymentStatus: 'Paid (UPI)',
        notes: 'Regular checkup.',
      ),
      CrmAppointment(
        id: 'APT20260909002',
        patientName: 'Priya Sharma',
        patientAge: '28 Y',
        patientGender: 'Female',
        patientPhone: '9123456789',
        patientEmail: 'priya@example.com',
        location: 'Kolkata, West Bengal',
        doctorName: 'Dr. Mehta',
        appointmentType: 'Follow Up',
        time: '09:30 AM',
        date: '09 Sep 2026',
        status: 'In Consultation',
        consultationFee: '₹ 500',
        paymentStatus: 'Paid (UPI)',
        notes: 'Patient coming for routine follow up.\nCheck previous reports.',
      ),
      CrmAppointment(
        id: 'APT20260909003',
        patientName: 'Suman Roy',
        patientAge: '45 Y',
        patientGender: 'Male',
        patientPhone: '9876543210',
        patientEmail: 'suman.roy@example.com',
        location: 'Kolkata, West Bengal',
        doctorName: 'Dr. Iyer',
        appointmentType: 'Diabetes Checkup',
        time: '10:00 AM',
        date: '09 Sep 2026',
        status: 'Scheduled',
        consultationFee: '₹ 800',
        paymentStatus: 'Pending',
        notes: 'First time visit for diabetes management.',
      ),
      CrmAppointment(
        id: 'APT20260909004',
        patientName: 'Neha Patel',
        patientAge: '31 Y',
        patientGender: 'Female',
        patientPhone: '9901122334',
        patientEmail: 'neha.p@example.com',
        location: 'Kolkata, West Bengal',
        doctorName: 'Dr. Sen',
        appointmentType: 'Thyroid Consultation',
        time: '10:30 AM',
        date: '09 Sep 2026',
        status: 'Scheduled',
        consultationFee: '₹ 600',
        paymentStatus: 'Paid (Card)',
        notes: 'Bring previous blood test reports.',
      ),
      CrmAppointment(
        id: 'APT20260909005',
        patientName: 'Karan Mehta',
        patientAge: '38 Y',
        patientGender: 'Male',
        patientPhone: '9123044567',
        patientEmail: 'karan.m@example.com',
        location: 'Kolkata, West Bengal',
        doctorName: 'Dr. Gupta',
        appointmentType: 'General Consultation',
        time: '11:00 AM',
        date: '09 Sep 2026',
        status: 'Scheduled',
        consultationFee: '₹ 500',
        paymentStatus: 'Pending',
        notes: 'Fever and cough.',
      ),
      CrmAppointment(
        id: 'APT20260909006',
        patientName: 'Anita Singh',
        patientAge: '26 Y',
        patientGender: 'Female',
        patientPhone: '9876509876',
        patientEmail: 'anita.s@example.com',
        location: 'Kolkata, West Bengal',
        doctorName: 'Dr. Mehta',
        appointmentType: 'Follow Up',
        time: '11:30 AM',
        date: '09 Sep 2026',
        status: 'Waiting',
        consultationFee: '₹ 400',
        paymentStatus: 'Paid (Cash)',
        notes: 'Check response to medication.',
      ),
      CrmAppointment(
        id: 'APT20260909007',
        patientName: 'Deepak Shaw',
        patientAge: '52 Y',
        patientGender: 'Male',
        patientPhone: '9830098765',
        patientEmail: 'deepak.s@example.com',
        location: 'Howrah, West Bengal',
        doctorName: 'Dr. Sen',
        appointmentType: 'BP Checkup',
        time: '12:00 PM',
        date: '09 Sep 2026',
        status: 'Waiting',
        consultationFee: '₹ 500',
        paymentStatus: 'Paid (UPI)',
        notes: 'Blood pressure monitoring.',
      ),
      CrmAppointment(
        id: 'APT20260909008',
        patientName: 'Pooja Verma',
        patientAge: '29 Y',
        patientGender: 'Female',
        patientPhone: '9123098734',
        patientEmail: 'pooja.v@example.com',
        location: 'Salt Lake, Kolkata',
        doctorName: 'Dr. Iyer',
        appointmentType: 'Pregnancy Consultation',
        time: '12:30 PM',
        date: '09 Sep 2026',
        status: 'Scheduled',
        consultationFee: '₹ 1000',
        paymentStatus: 'Pending',
        notes: 'First trimester checkup.',
      ),
      CrmAppointment(
        id: 'APT20260909009',
        patientName: 'Amit Kumar',
        patientAge: '41 Y',
        patientGender: 'Male',
        patientPhone: '9901198765',
        patientEmail: 'amit.k@example.com',
        location: 'Kolkata, West Bengal',
        doctorName: 'Dr. Gupta',
        appointmentType: 'General Consultation',
        time: '01:00 PM',
        date: '09 Sep 2026',
        status: 'Cancelled',
        consultationFee: '₹ 500',
        paymentStatus: 'Refunded',
        notes: 'Patient requested cancellation.',
      ),
      CrmAppointment(
        id: 'APT20260909010',
        patientName: 'Rita Ghosh',
        patientAge: '36 Y',
        patientGender: 'Female',
        patientPhone: '9876512345',
        patientEmail: 'rita.g@example.com',
        location: 'Kolkata, West Bengal',
        doctorName: 'Dr. Mehta',
        appointmentType: 'Follow Up',
        time: '01:30 PM',
        date: '09 Sep 2026',
        status: 'Scheduled',
        consultationFee: '₹ 400',
        paymentStatus: 'Paid (Card)',
        notes: '',
      ),
    ];
  }

  static Future<List<CrmDoctor>> getDoctors() async {
    await Future.delayed(const Duration(milliseconds: 500));
    return [
      CrmDoctor(
        id: 'DOC001',
        name: 'Dr. Arindam Sen',
        specialization: 'General Physician',
        phone: '9830011223',
        email: 'arindam.sen@example.com',
        consultationFee: '₹ 500',
        availabilityDays: 'Mon - Sat',
        availabilityTime: '9:00 AM - 5:00 PM',
        status: 'Active',
        avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
      ),
      CrmDoctor(
        id: 'DOC002',
        name: 'Dr. Priya Mehta',
        specialization: 'Gynecologist',
        phone: '9123456789',
        email: 'priya.mehta@example.com',
        consultationFee: '₹ 700',
        availabilityDays: 'Mon, Wed, Fri',
        availabilityTime: '10:00 AM - 4:00 PM',
        status: 'Active',
        avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
      ),
      CrmDoctor(
        id: 'DOC003',
        name: 'Dr. Karan Gupta',
        specialization: 'Pediatrician',
        phone: '9876509876',
        email: 'karan.gupta@example.com',
        consultationFee: '₹ 600',
        availabilityDays: 'Tue - Sat',
        availabilityTime: '9:00 AM - 3:00 PM',
        status: 'Active',
        avatarUrl: 'https://randomuser.me/api/portraits/men/46.jpg',
      ),
      CrmDoctor(
        id: 'DOC004',
        name: 'Dr. Neha Sharma',
        specialization: 'Dermatologist',
        phone: '9901122334',
        email: 'neha.sharma@example.com',
        consultationFee: '₹ 800',
        availabilityDays: 'Mon, Tue, Thu, Sat',
        availabilityTime: '11:00 AM - 5:00 PM',
        status: 'Active',
        avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
      ),
      CrmDoctor(
        id: 'DOC005',
        name: 'Dr. Suman Roy',
        specialization: 'Cardiologist',
        phone: '9830098765',
        email: 'suman.roy@example.com',
        consultationFee: '₹ 900',
        availabilityDays: 'Mon - Fri',
        availabilityTime: '9:00 AM - 4:00 PM',
        status: 'On Leave',
        avatarUrl: 'https://randomuser.me/api/portraits/women/24.jpg',
      ),
      CrmDoctor(
        id: 'DOC006',
        name: 'Dr. Amit Kumar',
        specialization: 'Orthopedic',
        phone: '9876123456',
        email: 'amit.kumar@example.com',
        consultationFee: '₹ 700',
        availabilityDays: 'Tue, Thu, Sat',
        availabilityTime: '10:00 AM - 5:00 PM',
        status: 'Active',
        avatarUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
      ),
      CrmDoctor(
        id: 'DOC007',
        name: 'Dr. Ritu Ghosh',
        specialization: 'ENT Specialist',
        phone: '9830045678',
        email: 'ritu.ghosh@example.com',
        consultationFee: '₹ 600',
        availabilityDays: 'Mon - Sat',
        availabilityTime: '9:00 AM - 1:00 PM',
        status: 'Active',
        avatarUrl: 'https://randomuser.me/api/portraits/women/11.jpg',
      ),
      CrmDoctor(
        id: 'DOC008',
        name: 'Dr. Deepak Shaw',
        specialization: 'Ophthalmologist',
        phone: '9830987654',
        email: 'deepak.shaw@example.com',
        consultationFee: '₹ 700',
        availabilityDays: 'Mon, Wed, Fri',
        availabilityTime: '10:00 AM - 4:00 PM',
        status: 'Inactive',
        avatarUrl: 'https://randomuser.me/api/portraits/men/75.jpg',
      ),
      CrmDoctor(
        id: 'DOC009',
        name: 'Dr. Pooja Verma',
        specialization: 'Psychiatrist',
        phone: '9123098734',
        email: 'pooja.verma@example.com',
        consultationFee: '₹ 1000',
        availabilityDays: 'Tue - Sat',
        availabilityTime: '11:00 AM - 6:00 PM',
        status: 'Active',
        avatarUrl: 'https://randomuser.me/api/portraits/women/33.jpg',
      ),
      CrmDoctor(
        id: 'DOC010',
        name: 'Dr. Rajesh Iyer',
        specialization: 'Diabetologist',
        phone: '9876543210',
        email: 'rajesh.iyer@example.com',
        consultationFee: '₹ 700',
        availabilityDays: 'Mon - Fri',
        availabilityTime: '9:00 AM - 3:00 PM',
        status: 'Active',
        avatarUrl: 'https://randomuser.me/api/portraits/men/85.jpg',
      ),
    ];
  }

  static Future<List<CrmOrder>> getOrders() async {
    await Future.delayed(const Duration(milliseconds: 500));
    final defaultItems = [
      CrmOrderItem(
        name: 'Paracetamol 500mg',
        qty: 2,
        unitPrice: 25.00,
        amount: 50.00,
      ),
      CrmOrderItem(
        name: 'Vitamin D3 60K',
        qty: 1,
        unitPrice: 320.00,
        amount: 320.00,
      ),
      CrmOrderItem(
        name: 'Azithromycin 500mg',
        qty: 1,
        unitPrice: 120.00,
        amount: 120.00,
      ),
    ];
    return [
      CrmOrder(
        id: 'ORD000286',
        date: '09 Sep 2026',
        time: '10:15 AM',
        patientName: 'Rahul Das',
        itemsCount: '3 items',
        total: 1250.00,
        status: 'Delivered',
        source: 'App',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000285',
        date: '09 Sep 2026',
        time: '09:40 AM',
        patientName: 'Priya Sharma',
        itemsCount: '2 items',
        total: 640.00,
        status: 'In Transit',
        source: 'Website',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000284',
        date: '09 Sep 2026',
        time: '08:20 AM',
        patientName: 'Suman Roy',
        itemsCount: '5 items',
        total: 2380.00,
        status: 'Pending',
        source: 'Store',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000283',
        date: '08 Sep 2026',
        time: '07:10 PM',
        patientName: 'Neha Patel',
        itemsCount: '1 item',
        total: 320.00,
        status: 'Delivered',
        source: 'App',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000282',
        date: '08 Sep 2026',
        time: '05:45 PM',
        patientName: 'Karan Mehta',
        itemsCount: '4 items',
        total: 1980.00,
        status: 'In Transit',
        source: 'Website',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000281',
        date: '08 Sep 2026',
        time: '03:30 PM',
        patientName: 'Anita Singh',
        itemsCount: '2 items',
        total: 760.00,
        status: 'Delivered',
        source: 'Store',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000280',
        date: '07 Sep 2026',
        time: '06:15 PM',
        patientName: 'Amit Kumar',
        itemsCount: '3 items',
        total: 1120.00,
        status: 'Cancelled',
        source: 'App',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000279',
        date: '07 Sep 2026',
        time: '01:20 PM',
        patientName: 'Rita Ghosh',
        itemsCount: '5 items',
        total: 3450.00,
        status: 'Delivered',
        source: 'Website',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000278',
        date: '07 Sep 2026',
        time: '11:10 AM',
        patientName: 'Deepak Shaw',
        itemsCount: '1 item',
        total: 280.00,
        status: 'Pending',
        source: 'Store',
        items: defaultItems,
      ),
      CrmOrder(
        id: 'ORD000277',
        date: '06 Sep 2026',
        time: '06:50 PM',
        patientName: 'Pooja Verma',
        itemsCount: '2 items',
        total: 890.00,
        status: 'Delivered',
        source: 'App',
        items: defaultItems,
      ),
    ];
  }
}
